# Generated by Django 4.1.1 on 2022-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_destination_desc_destination_idvalue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='desc',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='destination',
            name='thoughts',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
